module.exports = Object.freeze({
  UPDATE_SETTINGS: 'POWERCORD_SETTINGS_UPDATE',
  TOGGLE_SETTING: 'POWERCORD_SETTING_TOGGLE',
  UPDATE_SETTING: 'POWERCORD_SETTING_UPDATE',
  DELETE_SETTING: 'POWERCORD_SETTING_DELETE'
});
