module.exports = Object.freeze({
  FluxActions: {
    PLAYER_STATE_CHANGED: 'SPOTIFY_PLAYER_STATE_CHANGED',
    DEVICE_STATE_CHANGED: 'SPOTIFY_DEVICE_STATE_CHANGED',
    PLAYLIST_CREATE: 'SPOTIFY_PLAYLIST_CREATE',
    PLAYLIST_UPDATE: 'SPOTIFY_PLAYLIST_UPDATE',
    PLAYLIST_DELETE: 'SPOTIFY_PLAYLIST_DELETE',
    PLAYLIST_PURGE: 'SPOTIFY_PLAYLIST_PURGE'
  },
  SPOTIFY_BASE_URL: 'https://api.spotify.com/v1',
  SPOTIFY_PLAYER_URL: 'https://api.spotify.com/v1/me/player'
});
